### ISSUE TITLE
你好，win10上有异常提示

### ISSUE THREAD

**Issue by zhanxh** [xinliangnote/Go#1]
failed to rotate: failed to rename new symlink: rename F:/testlog.log.20191111.log_symlink F:/testlog.log: Access is denied.

**Comment by huchenghua** [comment]
Failed to write to log, invalid argument

**Comment by dzwvip** [comment]
日志中间件加了日志切割的hook以后的代码有问题，日志文件名如果不提前创建，会提示打开文件失败，而且每到打印日志时就会报错Failed to write to log, invalid argument。如果提前创建了，切割文件时就会报创建软链接失败，但是日志会写两份。带日期后缀的一份，原文件一份。openfile函数里不应该传filename

**Comment by xinliangnote** [comment]
日志这块，已修改，可以参考代码：https://github.com/xinliangnote/go-gin-api
