### ISSUE TITLE
日志记录问题

### ISSUE THREAD

**Issue by veryrich** [xinliangnote/Go#2]
您好，看了您关于日志记录的文章，很感谢非常有用，使用gin中间件的形式实现了router访问的日志记录，可是目前还是遇到了个问题，就是gin中间件的形式，只能记录访问日志，可是对于函数的错误是没有记录的，请问如果要记录函数的错误日志，可以使用中间件总的logger嘛？ 还是要重新 logger := logrus.new() 一个 重新配置

**Comment by xinliangnote** [comment]
可以使用初始化的 logger , 不要每次用的时候每次实例化，请参考下这个项目：https://github.com/xinliangnote/go-gin-api
